### ISSUE TITLE
API feedback

### ISSUE THREAD

**Issue by WillSewell** [barrucadu/pusher-ws#1]
Good job! I like how you've gone for a non callback based approach. Much nicer than our JS library ;)

Just had a quick look through the public functions. Here's some thoughts. Feel free to take or leave them :)
- `Key` is a very general name. I would stick to `AppKey`. It's also more consistent with our other libraries.
- Is there a reason why `Key` isn't another field of `Options` rather than an explicit parameter?
- The API is a little inconsistent in that some functions take `Pusher` as a parameter and some run in the `PusherClient` monad. I would stick to one of these. If you use `PusherClient` then I would make `runPusherClient` incorporate the behaviour of pusherWithKey.
- I find the second order higher order function `withConnection` confusing. It is not clear from its name or the docs why it is not just `(Connection -> IO ()`.
- Since you have an `Internal` module, I would stick more internal stuff in there, like the ping thread. Or split it into other modules that are not re-exported.

**Comment by barrucadu** [comment]
- The difference between the `Pusher` and `PusherClient` stuff is that the `Pusher`-taking stuff isn't exported, if you look at the docs (eg https://docs.barrucadu.co.uk/pusher-ws/Network-Pusher-WebSockets.html)
- I initially did have `pusherWithKey` take the action to run (although for a different reason), but it has the problem of what to do when the action terminates. There are three possibilities: leave the connection open, disconnect, or disconnect with blocking. I suppose the easiest choice would be to leave the connection open, and document that if the user doesn't explicitly disconnect, one of their event handlers will need to do that at some point.
- You're probably right about moving more internal stuff to an explicitly internal module. I think I'll add an unexported Network.Pusher.WebSockets.Client module to house most of the stuff currently in Network.Pusher.WebSockets

**Comment by barrucadu** [comment]
Ok, I think that's all the feedback addressed.

**Comment by WillSewell** [comment]
Ah yeah, I missed that the `Pusher` taking functions were not exported. In general I think it's a bit of a disadvantage of Haskell that the public/privateness of functions is not inline with the functions themselves.

I like the new module layout :)

Anyway, good job!
